title: Haziq Hurairah Ismail
logo:
description: Portfolio and Resume
show_downloads: true 
google_analytics: 
theme: jekyll-theme-minimal
remote_theme: pages-theme/minimal@v0.2.0
plugins:
-jekyll-remote-theme
